### ISSUE TITLE
Routing Error  uninitialized constant ApplicationController::ControllerAuthentication

### ISSUE THREAD

**Issue by doombug5000** [ryanb/nifty-generators#126]
Using Ruby 1.8.7
Rails 3.0.10

Fresh project used these commands:

rails new <projectname>
(configured database.yml)
rake db:create
(configured gemfile)
bundle install
rails generate controller home index
rails g nifty:layout
rails g nifty:authentication

and I get the above error when I try to view in browser (firefox).

I checked to make sure controller_authentication was present in the lib folder, it is.

I also checked to make sure config.autoload_paths was set to the lib folder in application.rb, it is as well.

I'm new at this so forgive me if I missed anything obvious, google searches and a search through this forum didn't come up with anything else.

EDIT: My own fault, needed to restart the server. Works fine. Apologies.

**Comment by agorinenko** [comment]
restart the server
