### ISSUE TITLE
Can't create a new user with Rails 3: uninitialized constant User::BCrypt 

### ISSUE THREAD

**Issue by palladius** [ryanb/nifty-generators#68]
Hi Ryan,
when I use Rails 3 with your (fabulous) nifty:authentication, and run proper migrations, then try to signup, I get this: 'uninitialized constant User::BCrypt'

I think the problem is NOT in your gem (googling for ruby forums), its rather in some external authentication module.  I just wanted to let you know.
## Everything works perfectly with previous rails 2.3.*

NameError in UsersController#create

uninitialized constant User::BCrypt

Rails.root: /Users/riccardo/git/ric_addressbook
Application Trace | Framework Trace | Full Trace

app/models/user.rb:30:in `prepare_password'
app/controllers/users_controller.rb:10:in`create'

activesupport (3.0.1) lib/active_support/callbacks.rb:414:in `_run_save_callbacks'
activerecord (3.0.1) lib/active_record/callbacks.rb:277:in`create_or_update'
activerecord (3.0.1) lib/active_record/persistence.rb:39:in `save'
activerecord (3.0.1) lib/active_record/validations.rb:43:in`save'
activerecord (3.0.1) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (3.0.1) lib/active_record/transactions.rb:237:in`save'
activerecord (3.0.1) lib/active_record/transactions.rb:289:in `with_transaction_returning_status'
activerecord (3.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:139:in`transaction'
activerecord (3.0.1) lib/active_record/transactions.rb:204:in `transaction'
activerecord (3.0.1) lib/active_record/transactions.rb:287:in`with_transaction_returning_status'
activerecord (3.0.1) lib/active_record/transactions.rb:237:in `save'
activerecord (3.0.1) lib/active_record/transactions.rb:248:in`rollback_active_record_state!'
activerecord (3.0.1) lib/active_record/transactions.rb:236:in `save'
actionpack (3.0.1) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.0.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.0.1) lib/abstract_controller/base.rb:150:in`process_action'
actionpack (3.0.1) lib/action_controller/metal/rendering.rb:11:in `process_action'
actionpack (3.0.1) lib/abstract_controller/callbacks.rb:18:in`process_action'
activesupport (3.0.1) lib/active_support/callbacks.rb:440:in `_run__434435962__process_action__1623385099__callbacks'
activesupport (3.0.1) lib/active_support/callbacks.rb:409:in`send'
activesupport (3.0.1) lib/active_support/callbacks.rb:409:in `_run_process_action_callbacks'
activesupport (3.0.1) lib/active_support/callbacks.rb:93:in`send'
activesupport (3.0.1) lib/active_support/callbacks.rb:93:in `run_callbacks'
actionpack (3.0.1) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
activesupport (3.0.1) lib/active_support/notifications.rb:52:in`instrument'
activesupport (3.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.0.1) lib/active_support/notifications.rb:52:in`instrument'
actionpack (3.0.1) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.0.1) lib/action_controller/metal/rescue.rb:17:in`process_action'
actionpack (3.0.1) lib/abstract_controller/base.rb:119:in `process'
actionpack (3.0.1) lib/abstract_controller/rendering.rb:40:in`process'
actionpack (3.0.1) lib/action_controller/metal.rb:133:in `dispatch'
actionpack (3.0.1) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
actionpack (3.0.1) lib/action_controller/metal.rb:173:in `action'
actionpack (3.0.1) lib/action_dispatch/routing/route_set.rb:62:in`call'
actionpack (3.0.1) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
actionpack (3.0.1) lib/action_dispatch/routing/route_set.rb:27:in`call'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:148:in `call'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:93:in`recognize'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:75:in `optimized_each'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:92:in`recognize'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:139:in `call'
actionpack (3.0.1) lib/action_dispatch/routing/route_set.rb:492:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
actionpack (3.0.1) lib/action_dispatch/middleware/head.rb:14:in`call'
rack (1.2.1) lib/rack/methodoverride.rb:24:in `call'
actionpack (3.0.1) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/flash.rb:182:in `call'
actionpack (3.0.1) lib/action_dispatch/middleware/session/abstract_store.rb:149:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/cookies.rb:287:in `call'
activerecord (3.0.1) lib/active_record/query_cache.rb:32:in`call'
activerecord (3.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
activerecord (3.0.1) lib/active_record/query_cache.rb:12:in`cache'
activerecord (3.0.1) lib/active_record/query_cache.rb:31:in `call'
activerecord (3.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/callbacks.rb:46:in `call'
activesupport (3.0.1) lib/active_support/callbacks.rb:415:in`_run_call_callbacks'
actionpack (3.0.1) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
rack (1.2.1) lib/rack/sendfile.rb:107:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.0.1) lib/action_dispatch/middleware/show_exceptions.rb:46:in`call'
railties (3.0.1) lib/rails/rack/logger.rb:13:in `call'
rack (1.2.1) lib/rack/runtime.rb:17:in`call'
activesupport (3.0.1) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.2.1) lib/rack/lock.rb:11:in`call'
rack (1.2.1) lib/rack/lock.rb:11:in `synchronize'
rack (1.2.1) lib/rack/lock.rb:11:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/static.rb:30:in `call'
railties (3.0.1) lib/rails/application.rb:168:in`call'
railties (3.0.1) lib/rails/application.rb:77:in `send'
railties (3.0.1) lib/rails/application.rb:77:in`method_missing'
railties (3.0.1) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.2.1) lib/rack/content_length.rb:13:in`call'
rack (1.2.1) lib/rack/handler/webrick.rb:52:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in`each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in`start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
rack (1.2.1) lib/rack/handler/webrick.rb:13:in`run'
rack (1.2.1) lib/rack/server.rb:213:in `start'
railties (3.0.1) lib/rails/commands/server.rb:65:in`start'
railties (3.0.1) lib/rails/commands.rb:30
railties (3.0.1) lib/rails/commands.rb:27:in `tap'
railties (3.0.1) lib/rails/commands.rb:27
script/rails:6:in`require'
script/rails:6

app/models/user.rb:30:in `prepare_password'
activesupport (3.0.1) lib/active_support/callbacks.rb:414:in`_run_save_callbacks'
activerecord (3.0.1) lib/active_record/callbacks.rb:277:in `create_or_update'
activerecord (3.0.1) lib/active_record/persistence.rb:39:in`save'
activerecord (3.0.1) lib/active_record/validations.rb:43:in `save'
activerecord (3.0.1) lib/active_record/attribute_methods/dirty.rb:21:in`save'
activerecord (3.0.1) lib/active_record/transactions.rb:237:in `save'
activerecord (3.0.1) lib/active_record/transactions.rb:289:in`with_transaction_returning_status'
activerecord (3.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:139:in `transaction'
activerecord (3.0.1) lib/active_record/transactions.rb:204:in`transaction'
activerecord (3.0.1) lib/active_record/transactions.rb:287:in `with_transaction_returning_status'
activerecord (3.0.1) lib/active_record/transactions.rb:237:in`save'
activerecord (3.0.1) lib/active_record/transactions.rb:248:in `rollback_active_record_state!'
activerecord (3.0.1) lib/active_record/transactions.rb:236:in`save'
app/controllers/users_controller.rb:10:in `create'
actionpack (3.0.1) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.0.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.0.1) lib/abstract_controller/base.rb:150:in`process_action'
actionpack (3.0.1) lib/action_controller/metal/rendering.rb:11:in `process_action'
actionpack (3.0.1) lib/abstract_controller/callbacks.rb:18:in`process_action'
activesupport (3.0.1) lib/active_support/callbacks.rb:440:in `_run__434435962__process_action__1623385099__callbacks'
activesupport (3.0.1) lib/active_support/callbacks.rb:409:in`send'
activesupport (3.0.1) lib/active_support/callbacks.rb:409:in `_run_process_action_callbacks'
activesupport (3.0.1) lib/active_support/callbacks.rb:93:in`send'
activesupport (3.0.1) lib/active_support/callbacks.rb:93:in `run_callbacks'
actionpack (3.0.1) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
activesupport (3.0.1) lib/active_support/notifications.rb:52:in`instrument'
activesupport (3.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.0.1) lib/active_support/notifications.rb:52:in`instrument'
actionpack (3.0.1) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.0.1) lib/action_controller/metal/rescue.rb:17:in`process_action'
actionpack (3.0.1) lib/abstract_controller/base.rb:119:in `process'
actionpack (3.0.1) lib/abstract_controller/rendering.rb:40:in`process'
actionpack (3.0.1) lib/action_controller/metal.rb:133:in `dispatch'
actionpack (3.0.1) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
actionpack (3.0.1) lib/action_controller/metal.rb:173:in `action'
actionpack (3.0.1) lib/action_dispatch/routing/route_set.rb:62:in`call'
actionpack (3.0.1) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
actionpack (3.0.1) lib/action_dispatch/routing/route_set.rb:27:in`call'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:148:in `call'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:93:in`recognize'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:75:in `optimized_each'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:92:in`recognize'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:139:in `call'
actionpack (3.0.1) lib/action_dispatch/routing/route_set.rb:492:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
actionpack (3.0.1) lib/action_dispatch/middleware/head.rb:14:in`call'
rack (1.2.1) lib/rack/methodoverride.rb:24:in `call'
actionpack (3.0.1) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/flash.rb:182:in `call'
actionpack (3.0.1) lib/action_dispatch/middleware/session/abstract_store.rb:149:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/cookies.rb:287:in `call'
activerecord (3.0.1) lib/active_record/query_cache.rb:32:in`call'
activerecord (3.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
activerecord (3.0.1) lib/active_record/query_cache.rb:12:in`cache'
activerecord (3.0.1) lib/active_record/query_cache.rb:31:in `call'
activerecord (3.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/callbacks.rb:46:in `call'
activesupport (3.0.1) lib/active_support/callbacks.rb:415:in`_run_call_callbacks'
actionpack (3.0.1) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
rack (1.2.1) lib/rack/sendfile.rb:107:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.0.1) lib/action_dispatch/middleware/show_exceptions.rb:46:in`call'
railties (3.0.1) lib/rails/rack/logger.rb:13:in `call'
rack (1.2.1) lib/rack/runtime.rb:17:in`call'
activesupport (3.0.1) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.2.1) lib/rack/lock.rb:11:in`call'
rack (1.2.1) lib/rack/lock.rb:11:in `synchronize'
rack (1.2.1) lib/rack/lock.rb:11:in`call'
actionpack (3.0.1) lib/action_dispatch/middleware/static.rb:30:in `call'
railties (3.0.1) lib/rails/application.rb:168:in`call'
railties (3.0.1) lib/rails/application.rb:77:in `send'
railties (3.0.1) lib/rails/application.rb:77:in`method_missing'
railties (3.0.1) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.2.1) lib/rack/content_length.rb:13:in`call'
rack (1.2.1) lib/rack/handler/webrick.rb:52:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in`each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in`start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
rack (1.2.1) lib/rack/handler/webrick.rb:13:in`run'
rack (1.2.1) lib/rack/server.rb:213:in `start'
railties (3.0.1) lib/rails/commands/server.rb:65:in`start'
railties (3.0.1) lib/rails/commands.rb:30
railties (3.0.1) lib/rails/commands.rb:27:in `tap'
railties (3.0.1) lib/rails/commands.rb:27
script/rails:6:in`require'
script/rails:6

---

riccardo@hansel:~/addressbook$ gem list |egrep 'rails|nifty|auth'
authlogic (2.1.6, 2.1.5)
nifty-generators (0.4.2, 0.4.1, 0.4.0)
rails (3.0.3, 3.0.1, 3.0.0, 2.3.9, 2.3.8, 2.3.5, 2.2.2, 1.2.2)

**Comment by hammady** [comment]
The bcrypt-ruby gem is now simply called bcrypt, so just write:
`gem "bcrypt"`
without the require

**Comment by javierrcc522** [comment]
@ejreynolds thank you so much sir, you fixed it
